# Generated by Django 4.0.3 on 2022-07-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LName', models.CharField(blank=True, max_length=100)),
                ('Fname', models.CharField(blank=True, max_length=100)),
                ('PAddress', models.CharField(blank=True, max_length=100)),
                ('Pnumber', models.IntegerField(blank=True)),
                ('Food', models.CharField(blank=True, max_length=100)),
                ('Order', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModPayDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DToday', models.DateField(blank=True, max_length=100)),
                ('DelToday', models.DateField(blank=True, max_length=100)),
                ('Mop', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
